name: "free14"
address: "https://cgc.chancloud.com/cgc/api/public/ai/server"
api_key: ""
enabled: true
default_weight: 10

limit:
  hourly: 100
  daily: 500
  monthly: 5000

thresholds:
  warning: 80
  critical: 95

use_proxy: false
use_sdk: false

model: "Nemotron-3-Super-120B-A12B"
available_models: []
use_weighted_model: false

response_format:
  content_fields: ['content']
  merge_fields: false
  use_reasoning_as_fallback: false

max_tokens: 1024